"""model tool knowledge enhance

Revision ID: a1b2c3d4e5f6
Revises: c6bcc2059365
Create Date: 2026-08-15 10:00:00.000000

新增：
- llm_models：模型管理（chat / embedding 分类）
- tools：工具库（http / mcp）
- knowledge_bases 增加切块策略与 embedding 模型列
- agent_runs 增加 call_type 列（invoke / stream）
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = 'c6bcc2059365'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=False),
    sa.Column('api_key', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_models_category'), 'llm_models', ['category'], unique=False)
    op.create_table('tools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tools_category'), 'tools', ['category'], unique=False)
    op.create_index(op.f('ix_tools_name'), 'tools', ['name'], unique=True)
    op.add_column('knowledge_bases', sa.Column('chunk_strategy', sa.String(length=16), server_default='auto', nullable=False))
    op.add_column('knowledge_bases', sa.Column('chunk_size', sa.Integer(), server_default='800', nullable=False))
    op.add_column('knowledge_bases', sa.Column('chunk_overlap', sa.Integer(), server_default='100', nullable=False))
    op.add_column('knowledge_bases', sa.Column('embedding_model_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_knowledge_bases_embedding_model_id', 'knowledge_bases', 'llm_models', ['embedding_model_id'], ['id'], ondelete='SET NULL')
    op.add_column('agent_runs', sa.Column('call_type', sa.String(length=16), server_default='invoke', nullable=False))
    op.create_index(op.f('ix_agent_runs_call_type'), 'agent_runs', ['call_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_runs_call_type'), table_name='agent_runs')
    op.drop_column('agent_runs', 'call_type')
    op.drop_constraint('fk_knowledge_bases_embedding_model_id', 'knowledge_bases', type_='foreignkey')
    op.drop_column('knowledge_bases', 'embedding_model_id')
    op.drop_column('knowledge_bases', 'chunk_overlap')
    op.drop_column('knowledge_bases', 'chunk_size')
    op.drop_column('knowledge_bases', 'chunk_strategy')
    op.drop_index(op.f('ix_tools_name'), table_name='tools')
    op.drop_index(op.f('ix_tools_category'), table_name='tools')
    op.drop_table('tools')
    op.drop_index(op.f('ix_llm_models_category'), table_name='llm_models')
    op.drop_table('llm_models')
    # ### end Alembic commands ###
